In [1]:
import random
import json
import pickle
import numpy as np
import nltk
from string import punctuation

In [10]:
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation
from tensorflow.keras.optimizers import SGD

In [3]:
DIR = './data/chatbot/'

In [4]:
with open(DIR + 'intents.json') as f:
    intents = json.loads(f.read())['intents']

In [5]:
words = []
documents = []
classes = []

lemmatizer = WordNetLemmatizer()

for intent in intents:
    for pattern in intent['patterns']:
        word_list = nltk.word_tokenize(pattern)
        words.extend(word_list)
        documents.append((word_list, intent['tag']))
        if intent['tag'] not in classes:
            classes.append(intent['tag'])

vocabulary = [lemmatizer.lemmatize(word) for word in words if word not in punctuation]
vocabulary = sorted(set(words))

In [36]:
training = []

for document in documents:
    bag = []
    text = document[0]
    text = [lemmatizer.lemmatize(word) for word in text]
    for word in words:
        bag.append(1) if word in text else bag.append(0)

    bag = np.array(bag, dtype=np.int8)
    binary_encoded_label = np.array([int(my_class == document[1]) for my_class in classes], dtype=np.int8)

    training.append(np.array([bag, binary_encoded_label]))

training = np.array(training)
random.shuffle(training)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [34]:
train_x = training[:, 0]
train_y = training[:, 1]

In [35]:
train_x

array([array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)                    ,
       array([0, 0, 0, 1, 1, 0, 0,